name: "Action test"
on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: "My Action"
        id: intro
        run: |
          echo "Action says: ${{ github.actor }} on ${{ runner.os }}"
          sleep 1
      - name: "Testing an Action"
        id: actiontime
        uses: "krayon-tests/action@d2363202bcc7e407b13eeb61ae808b5c4e386ee1"
        with:
          text: "This is my test action's test text"

