name: "Action test"
on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: "My Action"
        id: intro
        run: |
          echo "Action says: ${{ github.actor }} on ${{ runner.os }}"
          sleep 1
      - name: "Testing an Action"
        id: actiontime
        uses: "krayon-tests/action@75a18fcebd5962575ed6f871a9aadc1063017885"
        with:
          text: "This is my test action's test text"

